import { Geist, Geist_Mono, Alexandria } from "next/font/google";
import "./css/globals.css";

// Alexandria font from Google Fonts
const alexandria = Alexandria({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-alexandria",
  display: 'swap',
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${alexandria.variable} ${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}

